import {fetch} from 'common/js/Utils'

export default {
  getAllAuth (params) {
    var url = '/api/rbac/role/get_all_auth'
    console.log('params', url, params)
    return fetch(url, params)
    // return new Promise((resolve, reject) => {
    //   resolve([{
    //     'auth': 'user_management',
    //     'dependentAuths': [],
    //     'canDisabled': false,
    //     'label': '{{userManagement}}',
    //     'children': [{
    //       'auth': 'user_management_new_user',
    //       'dependentAuths': [],
    //       'canDisabled': true,
    //       'label': '{{userManagementNewUser}}',
    //       'children': []
    //     }, {
    //       'auth': 'user_management_search_user',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{userManagementSearchUser}}',
    //       'children': [{
    //         'auth': 'user_management_search_uid',
    //         'dependentAuths': ['user_management_list_uid'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchUid}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_email',
    //         'dependentAuths': ['user_management_list_email'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchEmail}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_status',
    //         'dependentAuths': ['user_management_list_status'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchStatus}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_create_time',
    //         'dependentAuths': ['user_management_list_create_time'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchCreateTime}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_creator',
    //         'dependentAuths': ['user_management_list_creator'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchCreator}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_user_role',
    //         'dependentAuths': ['user_management_list_user_role'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchUserRole}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_user_type',
    //         'dependentAuths': ['user_management_list_user_type'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchUserType}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_search_user_group',
    //         'dependentAuths': ['user_management_list_user_group'],
    //         'canDisabled': false,
    //         'label': '{{userManagementSearchUserGroup}}',
    //         'children': []
    //       }]
    //     }, {
    //       'auth': 'user_management_list_user',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{userManagementListUser}}',
    //       'children': [{
    //         'auth': 'user_management_list_uid',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListUid}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_email',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListEmail}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_status',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListStatus}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_create_time',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListCreateTime}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_creator',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListCreator}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_user_role',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListUserRole}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_user_type',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListUserType}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_list_user_group',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{userManagementListUserGroup}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_change_password',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{userManagementChangePassword}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_delete_user',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{userManagementDeleteUser}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_edit_group',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{userManagementEditGroup}}',
    //         'children': []
    //       }, {
    //         'auth': 'user_management_link_role',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{userManagementLinkRole}}',
    //         'children': []
    //       }]
    //     }]
    //   }, {
    //     'auth': 'group_management',
    //     'dependentAuths': [],
    //     'canDisabled': false,
    //     'label': '{{groupManagement}}',
    //     'children': [{
    //       'auth': 'group_management_new_group',
    //       'dependentAuths': [],
    //       'canDisabled': true,
    //       'label': '{{groupManagementNewGroup}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_move_subgroup',
    //       'dependentAuths': [],
    //       'canDisabled': true,
    //       'label': '{{groupManagementMoveSubgroup}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_move_group',
    //       'dependentAuths': ['group_management_edit_move_group'],
    //       'canDisabled': true,
    //       'label': '{{groupManagementMoveGroup}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_delete_group',
    //       'dependentAuths': [],
    //       'canDisabled': true,
    //       'label': '{{groupManagementDeleteGroup}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_edit_group',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{groupManagementEditGroup}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_edit_role',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{groupManagementEditRole}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_edit_member',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{groupManagementEditMember}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_edit_move_group',
    //       'dependentAuths': ['group_management_move_group'],
    //       'canDisabled': false,
    //       'label': '{{groupManagementEditMoveGroup}}',
    //       'children': []
    //     }, {
    //       'auth': 'group_management_search_group',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{groupManagementSearchGroup}}',
    //       'children': [{
    //         'auth': 'group_management_search_group_name',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{groupManagementSearchGroupName}}',
    //         'children': []
    //       }, {
    //         'auth': 'group_management_search_create_time',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{groupManagementSearchCreateTime}}',
    //         'children': []
    //       }, {
    //         'auth': 'group_management_search_creator',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{groupManagementSearchCreator}}',
    //         'children': []
    //       }, {
    //         'auth': 'group_management_search_group_role',
    //         'dependentAuths': ['group_management_edit_role'],
    //         'canDisabled': false,
    //         'label': '{{groupManagementSearchGroupRole}}',
    //         'children': []
    //       }]
    //     }]
    //   }, {
    //     'auth': 'role_management',
    //     'dependentAuths': [],
    //     'canDisabled': false,
    //     'label': '{{roleManagement}}',
    //     'children': [{
    //       'auth': 'role_management_new_role',
    //       'dependentAuths': [],
    //       'canDisabled': true,
    //       'label': '{{roleManagementNewRole}}',
    //       'children': []
    //     }, {
    //       'auth': 'role_management_search_role',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{roleManagementSearchRole}}',
    //       'children': [{
    //         'auth': 'role_management_search_role_name',
    //         'dependentAuths': ['role_management_list_role_name'],
    //         'canDisabled': false,
    //         'label': '{{roleManagementSearchRoleName}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_search_create_time',
    //         'dependentAuths': ['role_management_list_create_time'],
    //         'canDisabled': false,
    //         'label': '{{roleManagementSearchCreateTime}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_search_creator',
    //         'dependentAuths': ['role_management_list_creator'],
    //         'canDisabled': false,
    //         'label': '{{roleManagementSearchCreator}}',
    //         'children': []
    //       }]
    //     }, {
    //       'auth': 'role_management_list_role',
    //       'dependentAuths': [],
    //       'canDisabled': false,
    //       'label': '{{roleManagementListRole}}',
    //       'children': [{
    //         'auth': 'role_management_list_role_name',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{roleManagementListRoleName}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_list_create_time',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{roleManagementListCreateTime}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_list_creator',
    //         'dependentAuths': [],
    //         'canDisabled': false,
    //         'label': '{{roleManagementListCreator}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_link_user',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{roleManagementLinkUser}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_copy_role',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{roleManagementCopyRole}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_delete_role',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{roleManagementDeleteRole}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_manage_auth',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{roleManagementManageAuth}}',
    //         'children': []
    //       }, {
    //         'auth': 'role_management_list_edit_time',
    //         'dependentAuths': [],
    //         'canDisabled': true,
    //         'label': '{{roleManagementListEditTime}}',
    //         'children': []
    //       }]
    //     }]
    //   }])
    // })
  },
  getCurrency (params) {
    var url = '/api/resource/accountset/get_all_currency'
    console.log('params', url, params)
    return fetch(url, params)
  },
  saveCurrency (params) {
    var url = '/api/resource/config/edit_exchangeRate_setting'
    console.log('params', url, params)
    return fetch(url, params)
  },
  getList (params) {
    var url = '/api/resource/config/get_exchangeRate_setting_list'
    console.log('params', url, params)
    return fetch(url, params)
  },
  deleteCurrency (params) {
    var url = '/api/resource/config/delete_exchangeRate_setting'
    console.log('params', url, params)
    return fetch(url, params)
  }

}
