var all = {
  'zh-CN': {
    memberProfile: '会员概览',
    profile: '概要',
    inviteCode: '邀请码',
    layout: '层次',
    teamAmount: '团队总数',
    newValidMembers: '新增有效一代会员量',
    teamTradeAccountAmount: '团队交易账号总交易量',
    personalInsuranceAccountAmount: '个人保险账号总入金量',
    firstInsuranceAccountAmount: '一代保险账号总入金',
    teamInsuranceAccountAmount: '团队保险账号总入金量',
    level1: '第一代',
    level2: '第二代',
    level3: '第三代',
    level4: '第四代',
    level5: '第五代',
    level6: '第六代',
    level7: '第七代',
    level8: '第八代',
    level9: '第九代',
    inviteLink: '邀请链接',
    copy: '复制',
    totalAmount: '总人数',
    person: '人',
    dallor: '$',
    tradeAmount: '交易账号总交易量',
    insuranceAmount: '保险账号总入金量'
  },
  'zh-TW': {
    memberProfile: '會員概覽',
    profile: '概要',
    inviteCode: '邀請碼',
    layout: '層次',
    teamAmount: '團隊總數',
    newValidMembers: '新增有效一代會員量',
    teamTradeAccountAmount: '團隊交易賬號縂交易量',
    personalInsuranceAccountAmount: '個人保險賬號縂入金量',
    firstInsuranceAccountAmount: '一代保險賬號縂入金',
    teamInsuranceAccountAmount: '團隊保險賬號縂入金量',
    level1: '第一代',
    level2: '第二代',
    level3: '第三代',
    level4: '第四代',
    level5: '第五代',
    level6: '第六代',
    level7: '第七代',
    level8: '第八代',
    level9: '第九代',
    inviteLink: '邀請鏈接',
    copy: '複製',
    totalAmount: '總人數',
    tradeAmount: '交易賬號縂交易量',
    insuranceAmount: '保險賬號縂交易量'
  },
  'en': {
    memberProfile: 'Member Overview',
    profile: 'Profile',
    inviteCode: 'Invitation Code',
    layout: 'Level',
    teamAmount: 'Total Number of Team',
    newValidMembers: 'New Activated Direct Level Members',
    teamTradeAccountAmount: 'Total Trading Volume of Team Trading Account',
    personalInsuranceAccountAmount: 'Total Deposit of Personal Assurance Account',
    firstInsuranceAccountAmount: 'Total Deposit of Direct Level Assurance Account',
    teamInsuranceAccountAmount: 'Total Deposit of Team Assurance Account ',
    level1: 'First Level',
    level2: 'Second Level',
    level3: 'Third Level',
    level4: 'Fourth Level',
    level5: 'Fifth Level',
    level6: 'Sixth Level',
    level7: 'Seventh Level',
    level8: 'Eighth Level',
    level9: 'Ninth Level',
    inviteLink: 'Invitation Link',
    copy: 'Copy',
    totalAmount: 'Total Members',
    tradeAmount: 'Total Trading Volume of Trading Account ',
    insuranceAmount: 'Total Deposit of Insurance Account '
  }
}

import cookie from 'cookie'
var lang = cookie.get('lang') || 'en'
export default all[lang]
